/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PiCalculator;

import java.awt.Color;
import java.awt.Graphics2D;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import java.util.Random;
import java.lang.Math;

/**
 *
 * @author ldavis
 */
public class PiFront extends javax.swing.JFrame {

    /**
     * Creates new form PiFront
     */
    public PiFront() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        piImageLabel = new javax.swing.JLabel();
        piButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NtrialsEntry = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        piImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PiCalculator/pi.png"))); // NOI18N

        piButton.setText("Compute Pi");
        piButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piButtonActionPerformed(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(new javax.swing.border.MatteBorder(null));
        mainPanel.setMaximumSize(new java.awt.Dimension(300, 300));
        mainPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainPanelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jLabel1.setText("Number of trials:");

        NtrialsEntry.setText("Enter Number");
        NtrialsEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NtrialsEntryActionPerformed(evt);
            }
        });

        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        jLabel2.setText("(c) Luke Davis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(piImageLabel)
                            .addComponent(piButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NtrialsEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(piImageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(NtrialsEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void piButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piButtonActionPerformed
        // TODO add your handling code here:
        
        
        
        if(this.ntrials==0){
            JOptionPane.showMessageDialog(this, "Please enter number of trials!", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
      
        progressBar.setMinimum(0);
        progressBar.setMaximum(this.ntrials);
        progressBar.setValue(0);
        
        
        Graphics2D plt = (Graphics2D)mainPanel.getGraphics();
        
        setupCircle(plt);
        
        System.out.println("Computing Pi");
        
        Random rand = new Random();
        
        int in = 0;
        
         progressBar.setIndeterminate(true);
        
        for(int i=0;i<this.ntrials;i++){
           //System.out.print(Double.toString(rand.nextDouble())+'\n');
           
          double r1 = rand.nextDouble();
          double r2 =  rand.nextDouble();
          
          int rx = (int)(r1*this.mainPanel.getWidth()/2 + this.mainPanel.getWidth()/2);
          int ry = (int)(r2*this.mainPanel.getHeight()/2 + this.mainPanel.getHeight()/2);
          
         // int xint = rx - this.mainPanel.getWidth()/2;
         //int yint =this.mainPanel.getHeight()/2 - ry;
          
 
          double radius = Math.sqrt(r1*r1 + r2*r2);
        
          if(radius < 1.0)
          {
          plt.fillOval(rx, ry, 5, 5);
          in++;
          }
          
           
        }
        
        progressBar.setIndeterminate(false);
        progressBar.setValue(this.ntrials);
        
        pi = ((double)in/(double)this.ntrials)*4.0;
        
             
        outputArea.append("\nPi: \n"+pi);
        
    }//GEN-LAST:event_piButtonActionPerformed

    private void NtrialsEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NtrialsEntryActionPerformed
        // TODO add your handling code here:
        try{
        this.ntrials = parseInt(NtrialsEntry.getText());
        progressBar.setMinimum(0);
        progressBar.setMaximum(this.ntrials);
        progressBar.setIndeterminate(false);
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this,"Number of trials must be an integer", "Error", JOptionPane.ERROR_MESSAGE);
            nfe.getMessage();
        }
        
    }//GEN-LAST:event_NtrialsEntryActionPerformed

    private void mainPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseEntered
        // TODO add your handling code here:
     Graphics2D plt = (Graphics2D)mainPanel.getGraphics();
        
        setupCircle(plt);
     
    }//GEN-LAST:event_mainPanelMouseEntered

    private void setupCircle(Graphics2D g)
    {
        int dia = mainPanel.getWidth();
        
        int center = mainPanel.getWidth()/2;
       
       g.setColor(Color.WHITE);
      g.fillRect(center - dia/2,center - dia/2, dia, dia);
        
       g.setColor(Color.BLACK);
       
        g.drawOval(center - dia/2,center - dia/2, dia, dia);
        g.drawLine(0, center, center*2, center);
        g.drawLine(center, 0, center, center*2);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PiFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PiFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PiFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PiFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PiFront().setVisible(true);
            }
        });
        
        
    }

   private int ntrials = 0;
   private double pi;
   private final double PI = 3.14159265359;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NtrialsEntry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JButton piButton;
    private javax.swing.JLabel piImageLabel;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
